"""DEMO/SHOWCASE SEED - Policy Robustness cards for Chennai DC.

WHY this exists: as of this seed's authoring, every real, live-computed
Chennai DC SKU/node pair lands in a non-actionable governance tier
(`no_change_needed` or `no_better_alternative_found` - confirmed via
GET /policy/recommendations before writing this script), so the "Waiting for
Approval" and "Auto-Approved" filters have nothing to show for a Chennai
demo/presentation session. This script hand-authors a small, clearly-flagged
set of override rows for a handful of REAL Chennai SKUs so those filters have
representative cards to present - the SAME honesty discipline this project
already applies to simulated demand/lead-time history (Phase 3/4/5): clearly
documented as seeded/demo, isolated from the real computation pipeline, and
identifiable/removable at the DATA level via `is_demo_seed=True` on both
PolicyRecommendation and PolicyChangeAuditLog (see migration
0010_demo_seed_flag) - not just by convention or a code comment.

What is REAL vs DEMO in each row:
  - sku_code, node, current_policy_type/current_params (Part A) or
    old_policy_type/old_params (Part B): REAL - read from this SKU's actual
    latest PolicySnapshot via policy_recommendation_service.build_context,
    unchanged.
  - suggested_policy_type/suggested_params (Part A) or new_policy_type/
    new_params (Part B): the TYPE is a demo choice (picked for variety across
    all 5 policy types); the concrete PARAMS are computed by the real
    `policy_service.policy_params_for_type()` formula against this SKU's real
    inputs - so they are structurally/numerically the same kind of number the
    real engine would have produced for that candidate type, just not
    selected as the actual highest-scorer.
  - All Robustness Score components/composites, service levels, and cost
    breakdowns: DEMO, hand-authored to land in the ranges the showcase needs
    (current 40-79 / suggested 80-96 for Part A, old <40 / new 80-96 for Part
    B) - and INTERNALLY CONSISTENT: each composite is computed from its own
    component scores via the exact real weighting formula (see `_composite`
    below, mirroring robustness_service.compute_robustness_score's weights),
    so a card's header score always matches the sum of its own displayed
    components, and a suggested/new score is always higher than the
    current/old one it replaces (never the "suggested scores lower" bug this
    project fixed for real data).
  - reasoning text: generated by the REAL
    policy_recommendation_service.build_reasoning() using this SKU's real
    classification/volatility/cost-percentile context, just narrating the
    DEMO scores - so it reads exactly like a real card's reasoning.

Isolation from the real pipeline: refresh_recommendations() skips any
SKU/node pair whose existing PolicyRecommendation row already has
is_demo_seed=True (see policy_recommendation_service.py) - a real network-wide
re-evaluation can never overwrite these rows. This script is also idempotent
(safe to re-run any time, e.g. after a real recalculation, to restore the
showcase rows if they were ever removed) - it upserts by (sku_code,
node_code) and replaces its own prior demo audit-log rows rather than
accumulating duplicates.

Run once: `python -m app.seed.demo_robustness_showcase` (or via
`docker compose exec api python -m app.seed.demo_robustness_showcase`).

To remove this showcase later: delete WHERE is_demo_seed = true from both
policy_recommendations and policy_change_audit_log, then re-run
POST /policy/recommendations/refresh so those SKU/node pairs get a real
evaluation again.
"""
import uuid
from datetime import date, datetime, timedelta
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.session import SessionLocal
from app.models import PolicyChangeAuditLog, PolicyRecommendation
from app.services import policy_recommendation_service as recsvc
from app.services import robustness_service
from app.services.policy_service import POLICY_TYPES, policy_params_for_type

CHENNAI = "Chennai Distribution Center"

# component order matches robustness_service.compute_robustness_score's
# weights exactly: 0.30 service_stability, 0.25 stockout_resilience,
# 0.20 cost_stability, 0.15 expiry_robustness, 0.10 inventory_stability
_WEIGHTS = (0.30, 0.25, 0.20, 0.15, 0.10)


def _composite(components: tuple[float, float, float, float, float]) -> float:
    return sum(w * c for w, c in zip(_WEIGHTS, components))


def _component_dict(components: tuple[float, float, float, float, float]) -> dict:
    keys = ("service_stability", "stockout_resilience", "cost_stability", "expiry_robustness", "inventory_stability")
    return dict(zip(keys, components))


# ============================================================================
# PART A - "Waiting for Approval" showcase (suggest_pending_approval)
# 7 real Chennai SKUs, all currently no_better_alternative_found in real data.
# current components -> composite lands 40-79; suggested components -> 80-96.
# ============================================================================
PART_A = [
    # sku_code, suggested_policy_type, current_components, suggested_components,
    # current_service_level, suggested_service_level, current_total_cost, suggested_total_cost, cost_split
    dict(sku="SKU-2001", suggested_type="s_Q",
         current=(65, 60, 55, 80, 70), suggested=(95, 92, 88, 97, 90),
         current_sl=0.78, suggested_sl=0.96, current_cost=345000, suggested_cost=298000),
    dict(sku="SKU-2003", suggested_type="R_s_S",
         current=(55, 50, 45, 75, 60), suggested=(90, 88, 85, 95, 88),
         current_sl=0.71, suggested_sl=0.94, current_cost=412000, suggested_cost=356000),
    dict(sku="SKU-2005", suggested_type="base_stock",
         current=(70, 65, 60, 82, 72), suggested=(93, 90, 86, 96, 89),
         current_sl=0.80, suggested_sl=0.97, current_cost=298000, suggested_cost=261000),
    dict(sku="SKU-2011", suggested_type="s_S",
         current=(78, 74, 68, 85, 75), suggested=(96, 95, 92, 98, 94),
         current_sl=0.85, suggested_sl=0.99, current_cost=376000, suggested_cost=331000),
    dict(sku="SKU-2014", suggested_type="s_Q",
         current=(52, 48, 42, 72, 58), suggested=(85, 82, 78, 90, 84),
         current_sl=0.68, suggested_sl=0.91, current_cost=289000, suggested_cost=249000),
    dict(sku="SKU-2019", suggested_type="R_S",
         current=(72, 68, 62, 84, 70), suggested=(94, 91, 87, 96, 90),
         current_sl=0.82, suggested_sl=0.98, current_cost=421000, suggested_cost=364000),
    dict(sku="SKU-2027", suggested_type="R_s_S",
         current=(80, 76, 70, 88, 78), suggested=(95, 94, 90, 97, 92),
         current_sl=0.86, suggested_sl=0.98, current_cost=358000, suggested_cost=312000),
]

# ============================================================================
# PART B - "Auto-Approved" showcase (auto_changed, historical record)
# 6 DIFFERENT real Chennai SKUs. old components -> composite <40;
# new components -> 80-96. Each also gets a matching PolicyChangeAuditLog row.
# ============================================================================
PART_B = [
    dict(sku="SKU-2004", new_type="R_s_S",
         old=(35, 30, 25, 55, 40), new=(90, 87, 83, 93, 86),
         old_sl=0.52, new_sl=0.95, old_cost=298000, new_cost=241000, days_ago=5),
    dict(sku="SKU-2008", new_type="base_stock",
         old=(30, 25, 20, 50, 35), new=(94, 92, 89, 96, 90),
         old_sl=0.45, new_sl=0.97, old_cost=334000, new_cost=268000, days_ago=4),
    dict(sku="SKU-2013", new_type="s_S",
         old=(38, 33, 28, 58, 40), new=(87, 84, 80, 90, 83),
         old_sl=0.56, new_sl=0.93, old_cost=276000, new_cost=232000, days_ago=3),
    dict(sku="SKU-2032", new_type="s_Q",
         old=(32, 28, 22, 52, 36), new=(91, 89, 85, 94, 88),
         old_sl=0.49, new_sl=0.96, old_cost=402000, new_cost=337000, days_ago=6),
    dict(sku="SKU-2038", new_type="R_s_S",
         old=(22, 18, 15, 40, 25), new=(96, 95, 92, 98, 93),
         old_sl=0.38, new_sl=0.99, old_cost=389000, new_cost=305000, days_ago=2),
    dict(sku="SKU-2045", new_type="base_stock",
         old=(36, 32, 26, 58, 38), new=(83, 81, 77, 87, 80),
         old_sl=0.55, new_sl=0.90, old_cost=311000, new_cost=270000, days_ago=1),
]


def _resolve_type(preferred: str, current: str) -> str:
    """The base seed's initial policy-type assignment
    (policy_service.initial_policy_type_for_classification) is not guaranteed
    stable across a fresh reseed (no ORDER BY on the underlying pair query),
    so a hardcoded preferred type can coincidentally collide with whatever a
    SKU's real current type turns out to be this run - an illogical "switch
    to the same type" card. Falls back to the next type in POLICY_TYPES that
    isn't `current` when that happens, so the picked type always differs."""
    if preferred != current:
        return preferred
    for candidate in POLICY_TYPES:
        if candidate != current:
            return candidate
    raise RuntimeError("no alternative policy type available")  # unreachable: POLICY_TYPES has 5 entries


def _cost_split(total: float, holding_frac: float) -> tuple[float, float]:
    holding = round(total * holding_frac, 2)
    return holding, round(total - holding, 2)


async def _get_or_create(session: AsyncSession, sku_code: str, node_code: str) -> PolicyRecommendation:
    existing = (await session.scalars(
        select(PolicyRecommendation).where(PolicyRecommendation.sku_code == sku_code, PolicyRecommendation.node_code == node_code)
    )).first()
    if existing is None:
        existing = PolicyRecommendation(sku_code=sku_code, node_code=node_code)
        session.add(existing)
    return existing


async def seed_part_a(session: AsyncSession, as_of: date, computed_at: datetime, cost_pct: dict, vol_pct: dict):
    for row in PART_A:
        context = await recsvc.build_context(session, row["sku"], CHENNAI, as_of)
        if context is None:
            raise RuntimeError(f"No PolicySnapshot/cost/sku context for {row['sku']} at {CHENNAI} - seed real data first")

        current_composite = _composite(row["current"])
        suggested_composite = _composite(row["suggested"])
        assert 40 <= current_composite <= 79, f"{row['sku']} current composite {current_composite} out of 40-79 range"
        assert 80 <= suggested_composite <= 96, f"{row['sku']} suggested composite {suggested_composite} out of 80-96 range"
        assert suggested_composite > current_composite

        suggested_type = _resolve_type(row["suggested_type"], context["current_policy_type"])
        suggested_params = policy_params_for_type(suggested_type, context["computed"])
        if suggested_type in {"s_S", "s_Q", "R_s_S", "base_stock"}:
            suggested_params["safetyStock"] = context["computed"]["safety_stock"]

        reasoning = recsvc.build_reasoning(
            classification=context["classification"], volatility_ratio=context["volatility_ratio"],
            volatility_p33=vol_pct["p33"], volatility_p67=vol_pct["p67"],
            trend=context["trend"], cadence_days=context["cadence_days"], unit_cost=context["unit_cost"],
            median_cost=cost_pct["median"], p90_cost=cost_pct["p90"],
            current_policy_type=context["current_policy_type"], current_score=current_composite,
            governance_action="suggest_pending_approval",
            suggested_policy_type=suggested_type, suggested_score=suggested_composite,
        )

        current_holding, current_shortage = _cost_split(row["current_cost"], 0.84)
        suggested_holding, suggested_shortage = _cost_split(row["suggested_cost"], 0.93)

        rec = await _get_or_create(session, row["sku"], CHENNAI)
        rec.computed_at = computed_at
        rec.current_policy_type = context["current_policy_type"]
        rec.current_params = context["current_params"]
        rec.reasoning = reasoning
        rec.governance_action = "suggest_pending_approval"
        cc = _component_dict(row["current"])
        rec.current_composite_score = round(current_composite, 2)
        rec.current_service_stability = round(cc["service_stability"], 2)
        rec.current_stockout_resilience = round(cc["stockout_resilience"], 2)
        rec.current_cost_stability = round(cc["cost_stability"], 2)
        rec.current_expiry_robustness = round(cc["expiry_robustness"], 2)
        rec.current_inventory_stability = round(cc["inventory_stability"], 2)
        rec.current_service_level_achieved = round(row["current_sl"], 4)
        rec.current_total_cost = row["current_cost"]
        rec.current_total_holding_cost = current_holding
        rec.current_total_shortage_cost = current_shortage

        sc = _component_dict(row["suggested"])
        rec.suggested_policy_type = suggested_type
        rec.suggested_params = suggested_params
        rec.suggested_composite_score = round(suggested_composite, 2)
        rec.suggested_service_stability = round(sc["service_stability"], 2)
        rec.suggested_stockout_resilience = round(sc["stockout_resilience"], 2)
        rec.suggested_cost_stability = round(sc["cost_stability"], 2)
        rec.suggested_expiry_robustness = round(sc["expiry_robustness"], 2)
        rec.suggested_inventory_stability = round(sc["inventory_stability"], 2)
        rec.suggested_service_level_achieved = round(row["suggested_sl"], 4)
        rec.suggested_total_cost = row["suggested_cost"]
        rec.suggested_total_holding_cost = suggested_holding
        rec.suggested_total_shortage_cost = suggested_shortage
        rec.is_demo_seed = True


async def seed_part_b(session: AsyncSession, as_of: date, computed_at: datetime, cost_pct: dict, vol_pct: dict):
    for row in PART_B:
        context = await recsvc.build_context(session, row["sku"], CHENNAI, as_of)
        if context is None:
            raise RuntimeError(f"No PolicySnapshot/cost/sku context for {row['sku']} at {CHENNAI} - seed real data first")

        old_composite = _composite(row["old"])
        new_composite = _composite(row["new"])
        assert old_composite < 40, f"{row['sku']} old composite {old_composite} not below 40"
        assert 80 <= new_composite <= 96, f"{row['sku']} new composite {new_composite} out of 80-96 range"
        assert new_composite > old_composite

        new_type = _resolve_type(row["new_type"], context["current_policy_type"])
        new_params = policy_params_for_type(new_type, context["computed"])
        if new_type in {"s_S", "s_Q", "R_s_S", "base_stock"}:
            new_params["safetyStock"] = context["computed"]["safety_stock"]

        reasoning = recsvc.build_reasoning(
            classification=context["classification"], volatility_ratio=context["volatility_ratio"],
            volatility_p33=vol_pct["p33"], volatility_p67=vol_pct["p67"],
            trend=context["trend"], cadence_days=context["cadence_days"], unit_cost=context["unit_cost"],
            median_cost=cost_pct["median"], p90_cost=cost_pct["p90"],
            current_policy_type=context["current_policy_type"], current_score=old_composite,
            governance_action="auto_changed",
            suggested_policy_type=new_type, suggested_score=new_composite,
        )

        old_holding, old_shortage = _cost_split(row["old_cost"], 0.80)
        new_holding, new_shortage = _cost_split(row["new_cost"], 0.94)

        changed_at = computed_at - timedelta(days=row["days_ago"])

        rec = await _get_or_create(session, row["sku"], CHENNAI)
        rec.computed_at = computed_at
        rec.current_policy_type = context["current_policy_type"]
        rec.current_params = context["current_params"]
        rec.reasoning = reasoning
        rec.governance_action = "auto_changed"
        oc = _component_dict(row["old"])
        rec.current_composite_score = round(old_composite, 2)
        rec.current_service_stability = round(oc["service_stability"], 2)
        rec.current_stockout_resilience = round(oc["stockout_resilience"], 2)
        rec.current_cost_stability = round(oc["cost_stability"], 2)
        rec.current_expiry_robustness = round(oc["expiry_robustness"], 2)
        rec.current_inventory_stability = round(oc["inventory_stability"], 2)
        rec.current_service_level_achieved = round(row["old_sl"], 4)
        rec.current_total_cost = row["old_cost"]
        rec.current_total_holding_cost = old_holding
        rec.current_total_shortage_cost = old_shortage

        nc = _component_dict(row["new"])
        rec.suggested_policy_type = new_type
        rec.suggested_params = new_params
        rec.suggested_composite_score = round(new_composite, 2)
        rec.suggested_service_stability = round(nc["service_stability"], 2)
        rec.suggested_stockout_resilience = round(nc["stockout_resilience"], 2)
        rec.suggested_cost_stability = round(nc["cost_stability"], 2)
        rec.suggested_expiry_robustness = round(nc["expiry_robustness"], 2)
        rec.suggested_inventory_stability = round(nc["inventory_stability"], 2)
        rec.suggested_service_level_achieved = round(row["new_sl"], 4)
        rec.suggested_total_cost = row["new_cost"]
        rec.suggested_total_holding_cost = new_holding
        rec.suggested_total_shortage_cost = new_shortage
        rec.is_demo_seed = True

        # Idempotent audit log: replace this SKU/node's prior demo audit row(s)
        # rather than accumulating duplicates on repeated seed runs.
        prior = (await session.scalars(
            select(PolicyChangeAuditLog).where(
                PolicyChangeAuditLog.sku_code == row["sku"], PolicyChangeAuditLog.node_code == CHENNAI,
                PolicyChangeAuditLog.is_demo_seed == True,  # noqa: E712
            )
        )).all()
        for p in prior:
            await session.delete(p)

        session.add(PolicyChangeAuditLog(
            id=uuid.uuid4(), sku_code=row["sku"], node_code=CHENNAI,
            old_policy_type=context["current_policy_type"], old_params=context["current_params"],
            new_policy_type=new_type, new_params=new_params,
            robustness_score_at_change=round(old_composite, 2),
            changed_at=changed_at, changed_by=robustness_service.SYSTEM_CHANGED_BY,
            is_demo_seed=True,
        ))


async def seed_demo_robustness_showcase(session: AsyncSession):
    today = date.today()
    computed_at = datetime.now().replace(microsecond=0)
    cost_pct = await recsvc.cost_percentiles(session)
    vol_pct = await recsvc.volatility_percentiles(session)

    await seed_part_a(session, today, computed_at, cost_pct, vol_pct)
    await seed_part_b(session, today, computed_at, cost_pct, vol_pct)
    await session.commit()


async def main():
    async with SessionLocal() as session:
        await seed_demo_robustness_showcase(session)


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
